import { Produto } from '@/lib/types';

// Imagens públicas do Unsplash (dimensões fixas, sem expiração)
const IMG = {
  arroz:      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&h=800&fit=crop',
  feijao:     'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=800&h=800&fit=crop',
  oleo:       'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&h=800&fit=crop',
  cafe:       'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800&h=800&fit=crop',
  acucar:     'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=800&fit=crop',
  farinha:    'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&h=800&fit=crop',
  sabao:      'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=800&h=800&fit=crop',
  detergente: 'https://images.unsplash.com/photo-1528740561666-dc2479dc08ab?w=800&h=800&fit=crop',
  shampoo:    'https://images.unsplash.com/photo-1631730486784-74757d38e27f?w=800&h=800&fit=crop',
  leite:      'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&h=800&fit=crop',
  macarrao:   'https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&h=800&fit=crop',
  biscoito:   'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&h=800&fit=crop',
};

export const PRODUTOS_MOCK: Produto[] = [
  {
    id: 'mock-001',
    nome: 'Arroz Tipo 1 — 5kg',
    descricao: 'Arroz branco tipo 1, grão longo, ideal para o dia a dia. Cozimento rápido e sabor suave. Origem: Rio Grande do Sul.',
    preco: 24.90,
    categoria: 'Mercearia',
    imagens: [IMG.arroz],
    estoque: 50,
    ativo: true,
    destaque: true,
    promocao: false,
    peso: 5.2,
    altura: 10,
    largura: 30,
    comprimento: 20,
  },
  {
    id: 'mock-002',
    nome: 'Feijão Carioca — 1kg',
    descricao: 'Feijão carioca tipo 1, grão inteiro e selecionado. Rende mais e cozinha mais rápido. O clássico da mesa brasileira.',
    preco: 8.49,
    categoria: 'Mercearia',
    imagens: [IMG.feijao],
    estoque: 80,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 1.1,
    altura: 8,
    largura: 18,
    comprimento: 12,
  },
  {
    id: 'mock-003',
    nome: 'Óleo de Soja — 900ml',
    descricao: 'Óleo de soja refinado, zero colesterol, rico em vitamina E. Para fritar, refogar e temperar com leveza.',
    preco: 7.29,
    categoria: 'Mercearia',
    imagens: [IMG.oleo],
    estoque: 120,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 0.9,
    altura: 25,
    largura: 7,
    comprimento: 7,
  },
  {
    id: 'mock-004',
    nome: 'Café Torrado e Moído — 500g',
    descricao: 'Café premium, torra média, sabor encorpado e aroma intenso. Embalagem a vácuo para máxima frescura.',
    preco: 18.90,
    categoria: 'Mercearia',
    imagens: [IMG.cafe],
    estoque: 40,
    ativo: true,
    destaque: true,
    promocao: false,
    peso: 0.55,
    altura: 8,
    largura: 15,
    comprimento: 10,
  },
  {
    id: 'mock-005',
    nome: 'Açúcar Cristal — 2kg',
    descricao: 'Açúcar cristal granulado, de cana-de-açúcar selecionada. Para adoçar sucos, cafés e receitas caseiras.',
    preco: 11.50,
    categoria: 'Mercearia',
    imagens: [IMG.acucar],
    estoque: 60,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 2.1,
    altura: 8,
    largura: 20,
    comprimento: 14,
  },
  {
    id: 'mock-006',
    nome: 'Farinha de Trigo — 1kg',
    descricao: 'Farinha de trigo especial, enriquecida com ferro e ácido fólico. Ideal para pães, bolos, pizzas e massas caseiras.',
    preco: 5.90,
    categoria: 'Mercearia',
    imagens: [IMG.farinha],
    estoque: 90,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 1.1,
    altura: 8,
    largura: 18,
    comprimento: 12,
  },
  {
    id: 'mock-007',
    nome: 'Macarrão Espaguete — 500g',
    descricao: 'Macarrão espaguete nº 8 com ovos, textura al dente garantida. Combina com qualquer molho e fica pronto em 8 minutos.',
    preco: 4.49,
    categoria: 'Mercearia',
    imagens: [IMG.macarrao],
    estoque: 110,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 0.55,
    altura: 5,
    largura: 25,
    comprimento: 8,
  },
  {
    id: 'mock-008',
    nome: 'Leite Integral UHT — 1L',
    descricao: 'Leite integral UHT longa vida, fonte de cálcio e proteínas. Embalagem Tetra Pak, validade de 6 meses.',
    preco: 5.29,
    categoria: 'Laticínios',
    imagens: [IMG.leite],
    estoque: 200,
    ativo: true,
    destaque: true,
    promocao: false,
    peso: 1.05,
    altura: 20,
    largura: 7,
    comprimento: 7,
  },
  {
    id: 'mock-009',
    nome: 'Biscoito Recheado Chocolate — 140g',
    descricao: 'Biscoito recheado com cobertura de chocolate ao leite. Crocante por fora, cremoso por dentro. A preferência da criançada.',
    preco: 3.79,
    categoria: 'Mercearia',
    imagens: [IMG.biscoito],
    estoque: 150,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 0.2,
    altura: 5,
    largura: 18,
    comprimento: 10,
  },
  {
    id: 'mock-010',
    nome: 'Sabão em Pó — 1kg',
    descricao: 'Sabão em pó para roupas brancas e coloridas, fórmula com alvejante óptico. Remove manchas difíceis e perfuma as roupas.',
    preco: 13.90,
    categoria: 'Limpeza',
    imagens: [IMG.sabao],
    estoque: 70,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 1.1,
    altura: 10,
    largura: 20,
    comprimento: 14,
  },
  {
    id: 'mock-011',
    nome: 'Detergente Neutro — 500ml',
    descricao: 'Detergente líquido neutro, alta concentração, desgordurante eficaz. Não agride as mãos e não altera o sabor dos alimentos.',
    preco: 2.99,
    categoria: 'Limpeza',
    imagens: [IMG.detergente],
    estoque: 180,
    ativo: true,
    destaque: false,
    promocao: false,
    peso: 0.55,
    altura: 22,
    largura: 6,
    comprimento: 6,
  },
  {
    id: 'mock-012',
    nome: 'Shampoo Hidratante — 350ml',
    descricao: 'Shampoo com fórmula hidratante para cabelos ressecados e danificados. Com queratina e óleo de argan. Uso diário.',
    preco: 16.50,
    categoria: 'Higiene',
    imagens: [IMG.shampoo],
    estoque: 45,
    ativo: true,
    destaque: true,
    promocao: false,
    peso: 0.4,
    altura: 18,
    largura: 6,
    comprimento: 6,
  },
];
